// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


import type { Metadata } from 'next';
import './globals.css';

// export const metadata: Metadata = {
//   title: 'Market Captura — Capturing Markets Digitally',
//   description:
//     'Your full-stack marketing team under one roof. Strategy, content, execution & analytics — seamlessly integrated.',
//   keywords: 'digital marketing, social media marketing, brand identity, paid advertising, AI marketing, India',
//   openGraph: {
//     title: 'Market Captura',
//     description: 'Capturing markets digitally. One team. Full power. Zero gaps.',
//     url: 'https://marketcaptura.com',
//     siteName: 'Market Captura',
//     type: 'website',
//   },
// };

export const metadata: Metadata = {
  title: 'Market Captura — Capturing Markets Digitally',
  description:
    'Your full-stack marketing team under one roof.',
 icons: {
  icon: [
    { url: '/favicon.ico' },
    { url: '/icon.png', sizes: '32x32', type: 'image/png' },
  ],
}
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body>{children}</body>
    </html>
  );
}
